[package]
name = "landlord"
version = "0.1.7"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "publib"
path = "src/publib/lib.rs"

[[bin]]
name = "landlord"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.11.0"
clap = "2.33.1"
rood = { version = "0.2.0", features = ["serialization"] }
semver = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.114", features = ["derive"] }
sha2 = "0.9.1"
toml = "0.5.6"
toml_edit = "0.2.0"
