name = "landlord"
version = "0.1.0"
stack = "rust"

[[build]]
architecture = "amd64"
platform = "linux"

[[artifact]]
name = "landlord"
platforms = ["linux"]
path_template = "$(BUILD)/landlord"
include_checksum = false
