name = 'landlord'
version = '0.2.0'
stack = 'rust'
artifact_directory = 'artifacts'

[[build]]
architecture = 'amd64'
platform = 'linux'

[[build]]
architecture = 'arm64'
platform = 'darwin'

[[artifact]]
name = 'landlord'
include_checksum = true
path_template = '$(BUILD)/landlord'
target_name_template = 'landlord-$(PLATFORM)-$(ARCHITECTURE)'
